default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: fabio
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seguropitzi_development

test:
  <<: *default
  database: seguropitzi_test

production:
  <<: *default
  database: seguropitzi_production
  username: seguropitzi
  password: <%= ENV['SEGUROPITZI_DATABASE_PASSWORD'] %>
